name: macOS
on:
  workflow_dispatch:
jobs:
  make:
    strategy:
      fail-fast: false
      matrix:
        settings:
          - os: macos-12
            target: x86_64-apple-darwin
    runs-on: ${{ matrix.settings.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          path: src
      - name: "[Enclose.IO] Install dependencies"
        run: |
          # brew upgrade
          brew install squashfs
      - name: "[Enclose.IO] Set up rubyc"
        run: |
          curl -OL https://github.com/pmq20/ruby-packer/releases/download/darwin-x64/rubyc
          chmod +x rubyc
      - name: "[Enclose.IO] Set up Ruby"
        uses: ruby/setup-ruby@v1
        with:
          working-directory: src
      - name: "[Enclose.IO] Install rubocop"
        run: gem install rubocop
      - name: "[Enclose.IO] Run rubocop"
        run: |
          cd src
          rubocop
      - name: "[Enclose.IO] Check dependencies"
        run: |
          sw_vers
          uname -a
          uname -p
          uname -m
          sysctl -n machdep.cpu.brand_string
          which mksquashfs
          mksquashfs -version
          which ruby
          ruby -v
      - name: "[Enclose.IO] Bundle install"
        run: |
          cd src
          bundle install
      - name: "[Enclose.IO] MAIN"
        run: |
          export PATH="$(pwd):$PATH"
          cd src
          which rubyc
          rubyc --version
          rubyc bin/nodec -o pre-release-nodec-v140800.121803-darwin-x64
